name: edt
description: Emploi du temps à l'UPHF
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_login: ^4.1.1
  get_storage: ^2.1.1
  http: ^0.13.6
  intl: ^0.18.1
  path: ^1.8.3
  sqflite: ^2.2.8+4
  web_scraper: ^0.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/screens/UPHF_logo.png
